import collections
import usaddress
import os.path
from importlib import resources  # type: ignore[import]
import pandas  # type: ignore[import]
import string
from typing import Union

class AddressStandardizer:
    def __init__(self) -> None:
        self.__direction_abbrev_dict = dict
        self.__street_abbrev_dict = dict
        self.__unit_abbrev_dict = dict
        ...

    def __abbreviate_direction(self, direction: str) -> str: ...
    def __abbreviate_street_type(self, street_type: str) -> str: ...
    def __abbreviate_unit_type(self, street_type: str) -> str: ...
    def __break_up_block(self, text: str) -> str: ...
    def __build_direction_abbreviations_dict(self) -> dict: ...
    def __build_street_abbreviations_dict(self) -> dict: ...
    def __clean_text(self, text: str) -> str: ...
    def standardize_street_address(
        self, address: Union[str, list, pandas.Series]
    ) -> Union[str, list]: ...
