from typing import Any

class AddressStandardizer:
    __direction_abbrev_dict: dict
    __street_abbrev_dict: dict
    __unit_abbrev_dict: dict

    def __init__(self) -> None: ...
    def __abbreviate_direction(self, direction: str) -> str: ...
    def __abbreviate_street_type(self, street_type: str) -> str: ...
    def __abbreviate_unit_type(self, street_type: str) -> str: ...
    def __break_up_block(self, text: str) -> str: ...
    def __build_direction_abbreviations_dict(self) -> dict: ...
    def __build_street_abbreviations_dict(self) -> dict: ...
    def __clean_text(self, text: str) -> str: ...
    def standardize_street_address(
        self, address: str | list[Any] | Any
    ) -> str | list: ...
    def __standardize_street_address(self, address: str) -> str: ...
