from datetime import datetime as datetime
from typing import Union

def clean_up_date(input_string: Union[str, list]) -> Union[str, list]: ...
def clean_up_phone(input_string: Union[str, list]) -> Union[str, list]: ...
def clean_up_time(input_string: Union[str, list]) -> Union[str, list]: ...
