[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = 'REDCapUtilities'
version='1.4.8'
license= {file = 'LICENSE'}
readme = "README.md"
authors = [
    {name = "Kevin J. Delaney", email = "<kjdelaney@health.ucsd.edu>"},
]
description='Allows code reuse by other Python projects.'
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

[tool.coverage.report]
fail_under = 100
exclude_lines = [
    'if TYPE_CHECKING:',
    'pragma: no cover'
]

[tool.poetry]
name = "redcaputilities"
package-mode = true
packages = [{include = "redcaputilities", from = "src"}]

[project.urls]
documentation = "https://github.com/DBMI/REDCapUtilities"
homepage = "https://github.com/DBMI/REDCapUtilities"
repository = "https://github.com/DBMI/REDCapUtilities"

[tool.poetry.dependencies]
numpy = '>=2.4.2'
python = ">=3.11, <4.0"
pandas = ">=1.3.5"
python-dateutil = "^2.8.2"
pyyaml = "^6.0.1"
requests = ">=2.31.0"

[tool.poetry.group.dev.dependencies]
autoflake = "*"
make = "*"
mkdocs = "*"
mkdocstrings = "*"
mkdocs-material = "*"
openpyxl = "*"
pep8-naming = "*"
pre-commit = "*"
pymdown-extensions = "*"
pytest = "*"
pytest-github-actions-annotate-failures = "*"
pytest-cov = "*"
python-kacl = "*"
pyupgrade = "*"
ruff = "*"
setuptools = "<82"
typing = "*"
usaddress = "*"
wheel = "*"

[tool.pylint.format]
max-line-length="88"

[tool.pytest.ini_options]
addopts = """\
    --cov-report term-missing \
    --no-cov-on-fail \
"""
pythonpath = [".", "src"]
testpaths = ["tests"]
